name: dice_pro
description: A simple dice application. You can use normal dice, multi-walled dice or play dice poker.

version: 1.0.1+2

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  sliding_up_panel: ^2.0.0+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "images/dice_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  

  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: Lobster
      fonts:
        - asset: assets/Lobster-Regular.ttf
  uses-material-design: true

  assets:
    - images/
    - assets/